### ISSUE TITLE
Non integer strings are not accepted by R

### ISSUE THREAD

**Issue by KrisDavie** [vib-singlecell-nf/pcacv#8]
Python allows non integer strings to be used, whereas R does not. Providing a string as a seed causes R processes to crash.

R functions can use the following code to get a integer seed from a string:

```
if (params.global.seed instanceof String) {
    seed = params.global.seed.hashCode()
} else {
    seed = params.global.seed
}
```

**Comment by dweemx** [comment]
Hey @KrisDavie, 
Nice catch! Shouln't better have common seed instead of just handling this for R functions ?

**Comment by KrisDavie** [comment]
Yeah, actually it would be better for people wanting to use text seeds to use 
`'seed_goes_here'.hashCode()` in their params directly. 

We should at least have a check for params built in before other things run maybe. 
This didn't cause en error until very far into a pipeline for me, after cellranger and other stuff, and then because parseParams returns global, the process changes if you change the seed in the params, which would mean everything needs to be rerun

**Comment by KrisDavie** [comment]
Adding to this, just had this error after using `.hashCode()`: ` ValueError: Seed must be between 0 and 2**32 - 1` because the seed was negative. `.hashCode().abs()` should fix this.
